### ISSUE TITLE
Background images for slides?

### ISSUE THREAD

**Issue by geeohgeegeeoh** [jez/pandoc-starter#2]
Markdown->Pandoc-> reveal.js includes some basic guides on how to have a background image applied to the slides. 

It would help enormously with company policy if I could include the artwork which is in the Powerpoint Templates.

**Comment by jez** [comment]
Hm, this isn't something that I've needed to do before.

I'd bet that this is definitely *possible*, but I don't know off the top of my head how to get it working.

In particular, for this use case you might have to add some custom beamer styles. For example, [this is how][1] I customize beamer to change the background color and fonts in the `beamer-solarized` starter.

I'm curious to hear what you find out! And if you want, feel free to make a pull request to add a starter for it.

[1]: https://github.com/jez/pandoc-starter/blob/master/beamer-solarized/src/beamer-includes.tex

**Comment by geeohgeegeeoh** [comment]
https://tex.stackexchange.com/questions/7916/how-to-insert-a-background-image-in-a-beamer-frame
discusses some intracacies of this.

It looks to be stuff done low down inside beamer/TeX.

\usebackgroundtemplate gets set to include an image (from that thread)

% Now we install the new template for the following
frames:\usebackgroundtemplate{%
  \includegraphics[width=\paperwidth,height=\paperheight]{crayons}}
\begin{frame}
...\end{frame}


but comments suggest it can't be used with styled templates, set's BG
colour to white &c &c

I will play around. Thanks for your hints to explore. I will send a pull
request if I can make this work.

-G

**Comment by geeohgeegeeoh** [comment]
get the pandoc template for beamer.
```
mkdir -p ~/.pandoc/templates/
pandoc -D beamer > ~/.pandoc/templates/default.beamer
```

apply this diff
```
--- default.beamer.orig▷2018-02-21 14:25:52.000000000 +1000
+++ default.beamer▷⋅⋅⋅⋅⋅2018-02-21 14:20:27.000000000 +1000
@@ -83,6 +83,7 @@
 $endif$
 \fi
 $if(beamer)$
+\usebackgroundtemplate{\includegraphics[width=\paperwidth,height=\paperheight]{/tmp/brunsviga.jpg}}
 $if(theme)$
 \usetheme[$for(themeoptions)$$themeoptions$$sep$,$endfor$]{$theme$}
 $endif$
```

result: /tmp/brunsviga.jpg is minted behind every page, scaled to fit the page.

**Comment by geeohgeegeeoh** [comment]
I had to invoke pandoc with this extra option: ```--template ~/.pandoc/templates/default.beamer``` because for some reason, the modified, localized default.beamer template wasn't picked up. I am pretty sure the pandoc docs say this is where you put localized versions of templates.

**Comment by geeohgeegeeoh** [comment]
ok. With further work I found how to do this. no template modification required.

the Pandoc YAML permits direct injection of the underlying latex

```
header-includes:
    - \usebackgroundtemplate{\includegraphics[width=\paperwidth,height=\paperheight]{/tmp/brunsviga.jpg}}
```
You could elect to add some comment in README.md or other places or a new template instance showing how to do it, I may write one.

**Comment by jez** [comment]
Given how simple it is to do with the current templates, I think I just leave it out. Thanks for doing the research though!
